### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by MartinHajducik** [pipacsba/esphome_hunter_wifi#2]
Hi there ! 

This was exactly I was looking for. Would it be possible to describe how to integrate it with Smart Irrigation installed via HACS ?
I was able to install this external_component from main branch and configure yaml file  but I had to update yaml values little bit because I was getting warning during validation and now I am not sure whether everything is correct.

I do have Hunter X-Core with 8 valves.

this is how it looks now in my yaml file

`external_components:
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_hunter_wifi.git

hunter_wifi:
  pin: 16
  valves:
  - id: "lawn_sprinkler_valve_sw0"
    zone: 1
    max_duration_minutes: 10
  - id: "lawn_sprinkler_valve_sw1"
    zone: 2
    max_duration_minutes: 8`

I was expecting to see some switches or buttons, but so far nothing

Also this is how validation of yaml with additional generated values looks like 

`external_components:
- source:
    url: https://github.com/pipacsba/esphome_hunter_wifi.git
    type: git
  refresh: 1d
  components: all
hunter_wifi:
- pin:
    number: 16
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
  valves:
  - id:
      id: lawn_sprinkler_valve_sw0
      disabled_by_default: false
      restore_mode: ALWAYS_OFF
      name: lawn_sprinkler_valve_sw0
      internal: true
    zone: 1
    max_duration_minutes: 10
  - id:
      id: lawn_sprinkler_valve_sw1
      disabled_by_default: false
      restore_mode: ALWAYS_OFF
      name: lawn_sprinkler_valve_sw1
      internal: true
    zone: 2
    max_duration_minutes: 8
number: []
switch: []

INFO Configuration is valid!`

If you will be so kind to elaborate on this topic , I would be very grateful . 
Thanks a lot . 
Martin

**Comment by pipacsba** [comment]
Hi Martin,
this hunter-wifi integration strongly builds on the ESPhome "sprinkler" integration.
As I see it now, this information was completely missing from the documentation/example config - the latter one I have now updated.
Please give it a try - and let me know of the result. 
I hope the example config (which is now exactly the one I use) is as self-explanatory as I think!

Best,
Pipacsba

**Comment by MartinHajducik** [comment]
Hi,

Thanks for quick update. I have added missing lines, getting some yellow warnings, not sure whether that is something crucial to be fixed or not .. starting on line "Compiling .pioenvs/zavlaha/src/main.cpp.o" ends with line "#define HIGH true"

Yaml configuration

```
external_components:
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_hunter_wifi.git

sprinkler:
  - id: sprinkler_ctrlr
    main_switch: "Sprinklers"
    auto_advance_switch: "Sprinklers Auto Advance"
    valve_open_delay: 5s
    valves:
      - valve_switch: "Lawn Right Sprinklers"
        enable_switch: "Enable Lawn Right Sprinklers"
        #run_duration: 10min
        run_duration_number:
          name: "Lawn Right Run Duration"
          id: lawn_right_run_duration
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_right_sw
      - valve_switch: "Lawn Left Sprinklers"
        enable_switch: "Enable Lawn Left Sprinklers"
        #run_duration: 10min
        run_duration_number:
          name: "Lawn Left Run Duration"
          id: lawn_left_run_duration
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_left_sw
      - valve_switch: "Back Lawn Sprinklers"
        enable_switch: "Enable Back Lawn Sprinklers"
        #run_duration: 5min
        run_duration_number:
          name: "Back Lawn Run Duration"
          id: back_lawn_run_duration
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: back_lawn_sprinkler_valve_sw
      - valve_switch: "Front Lawn Sprinklers"
        enable_switch: "Enable Front Lawn Sprinklers"
        #run_duration: 5min
        run_duration_number:
          name: "Front Lawn Run Duration"
          id: front_lawn_run_duration
          initial_value: 5
          unit_of_measurement: min
        valve_switch_id: front_lawn_sprinkler_valve_sw
      - valve_switch: "Garden Sprinklers"
        enable_switch: "Enable Garden Sprinklers"
        #run_duration: 10min
        run_duration_number:
          name: "Garden Run Duration"
          id: garden_run_duration
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: garden_sprinkler_valve_sw

hunter_wifi:
  pin: 16
  valves:
    - id: "lawn_sprinkler_valve_right_sw"
      zone: 1
      max_duration_minutes: 30
      duration_number_name: lawn_right_run_duration
    - id: "lawn_sprinkler_valve_left_sw"
      zone: 2
      max_duration_minutes: 30
      duration_number_name: lawn_left_run_duration
    - id: "back_lawn_sprinkler_valve_sw"
      zone: 3
      max_duration_minutes: 15
      duration_number_name: back_lawn_run_duration
    - id: "front_lawn_sprinkler_valve_sw"
      zone: 4
      max_duration_minutes: 15
      duration_number_name: front_lawn_run_duration
    - id: "garden_sprinkler_valve_sw"
      zone: 5
      max_duration_minutes: 30
      duration_number_name: garden_run_duration
```


Install log 


```
INFO ESPHome 2024.6.2
INFO Reading configuration /config/esphome/zavlaha.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing zavlaha (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- noise-c @ 0.1.4
Compiling .pioenvs/zavlaha/src/main.cpp.o
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:51,
                 from src/esphome/components/logger/logger.h:12,
                 from src/esphome.h:19,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:41: warning: "LOW" redefined
 #define LOW               0x0
 
In file included from src/esphome.h:18,
                 from src/main.cpp:3:
src/esphome/components/hunter_wifi/hunter_wifi.h:17: note: this is the location of the previous definition
 #define LOW false
 
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:51,
                 from src/esphome/components/logger/logger.h:12,
                 from src/esphome.h:19,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:42: warning: "HIGH" redefined
 #define HIGH              0x1
 
In file included from src/esphome.h:18,
                 from src/main.cpp:3:
src/esphome/components/hunter_wifi/hunter_wifi.h:16: note: this is the location of the previous definition
 #define HIGH true
 
Linking .pioenvs/zavlaha/firmware.elf
RAM:   [=         ]  12.3% (used 40200 bytes from 327680 bytes)
Flash: [=====     ]  48.4% (used 887341 bytes from 1835008 bytes)
Building .pioenvs/zavlaha/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/zavlaha/firmware.bin"], [".pioenvs/zavlaha/firmware.elf"])
Wrote 0xea0c0 bytes to file /data/build/zavlaha/.pioenvs/zavlaha/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/zavlaha/firmware.bin"], [".pioenvs/zavlaha/firmware.elf"])
========================= [SUCCESS] Took 11.24 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.68.68
INFO Uploading /data/build/zavlaha/.pioenvs/zavlaha/firmware.bin (893120 bytes)
```
